### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Kederan** [CapnKitten/Spotify-Discord#6] opened 2019-09-14 00:09 UTC
**Which plugin is this about?**
Spotify-Discord

**Describe the Bug**
The last row of emojis is cut off when the theme is enabled with EmojiUtilies v0.0.6 by Zerebos.

**To Reproduce**
Enable and disable the theme.

**Expected Behavior**
Have the last row of emojis appear not cut off.

**Screenshots**
![2019-09-13_19-55-25](https://user-images.githubusercontent.com/19885815/64900923-4b4d3180-d662-11e9-9b7d-e4c4c6c5d76a.gif)

**Discord Version**
Stable

**Comment by CapnKitten** [comment] 2019-09-16 05:12
I'm not able to reproduce this, so let me know if it still persists with the latest update.

**Comment by Kederan** [comment] 2019-09-16 18:06
Thank you for the latest update.

Yes the bug still happens for me

![2019-09-16_14-05-33](https://user-images.githubusercontent.com/19885815/64981983-31dafe00-d88b-11e9-9d20-35b2ccfe4780.gif)

**Comment by CapnKitten** [comment] 2019-09-16 20:27
Are you using any emote plugins?

**Comment by Kederan** [comment] 2019-09-16 20:59
Yes this is the plugin: https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/EmojiUtilities

**Comment by CapnKitten** [comment] 2019-09-16 21:22
This has been fixed in v1.2.8.4

**Closed by CapnKitten** 2019-09-16 21:22 UTC
